export const dosageForms = [
  { name: "Tablet", description: "Solid oral dosage form" },
  { name: "Capsule", description: "Encapsulated oral dosage form" },
  { name: "Syrup", description: "Sweetened liquid oral preparation" },
  { name: "Suspension", description: "Liquid preparation with dispersed particles" },
  { name: "Drops", description: "Liquid preparation administered by drops" },
  { name: "Eye Drops", description: "Sterile drops for ophthalmic use" },
  { name: "Ear Drops", description: "Drops for otic use" },
  { name: "Cream", description: "Semi-solid topical preparation" },
  { name: "Ointment", description: "Greasy semi-solid topical preparation" },
  { name: "Gel", description: "Gel-based topical preparation" },
  { name: "Lotion", description: "Liquid topical preparation" },
  { name: "Inhaler", description: "Device-delivered inhalation product" },
  { name: "Nebule", description: "Liquid preparation for nebulization" },
  { name: "Injection", description: "Sterile injectable preparation" },
  { name: "Powder", description: "Dry powder preparation" },
  { name: "Gargle", description: "Liquid preparation for gargling" },
  { name: "Mouthwash", description: "Liquid preparation for oral rinsing" },
];
