export const genericDrugs = [
  { name: "Paracetamol", description: "Analgesic and antipyretic" },
  { name: "Ibuprofen", description: "NSAID for pain and inflammation" },
  { name: "Mefenamic Acid", description: "NSAID for pain relief" },
  { name: "Amoxicillin", description: "Penicillin-class antibiotic" },
  { name: "Cefalexin", description: "Cephalosporin antibiotic" },
  { name: "Azithromycin", description: "Macrolide antibiotic" },
  { name: "Cetirizine", description: "Antihistamine for allergy symptoms" },
  { name: "Loratadine", description: "Antihistamine for allergy symptoms" },
  { name: "Carbocisteine", description: "Mucolytic for productive cough" },
  { name: "Ambroxol", description: "Mucolytic and expectorant" },
  { name: "Salbutamol", description: "Bronchodilator for airway relief" },
  { name: "Losartan", description: "Antihypertensive angiotensin receptor blocker" },
  { name: "Amlodipine", description: "Calcium channel blocker for hypertension" },
  { name: "Metformin", description: "Oral antidiabetic medicine" },
  { name: "Omeprazole", description: "Proton pump inhibitor for acid control" },
  { name: "Loperamide", description: "Antidiarrheal medicine" },
  { name: "Domperidone", description: "Antiemetic and prokinetic medicine" },
  { name: "Ascorbic Acid", description: "Vitamin C supplement" },
  { name: "Ferrous Sulfate", description: "Iron supplement" },
  { name: "Clotrimazole", description: "Antifungal medicine" },
];
