export const productClassifications = [
  { name: "Antibiotic", description: "Products used to treat bacterial infections" },
  { name: "Antiviral", description: "Products used for viral infections" },
  { name: "Antifungal", description: "Products used for fungal infections" },
  { name: "Antihistamine", description: "Products used for allergy symptoms" },
  { name: "Analgesic", description: "Products used for pain relief" },
  { name: "Antipyretic", description: "Products used to reduce fever" },
  { name: "NSAID", description: "Non-steroidal anti-inflammatory products" },
  { name: "Antitussive", description: "Products used to suppress cough" },
  { name: "Mucolytic", description: "Products used to loosen mucus" },
  { name: "Nasal Decongestant", description: "Products used for nasal congestion" },
  { name: "Bronchodilator", description: "Products used to open airways" },
  { name: "Antacid", description: "Products used to neutralize stomach acid" },
  { name: "Anti-ulcer", description: "Products used for ulcer and acid control" },
  { name: "Antidiarrheal", description: "Products used for diarrhea management" },
  { name: "Antiemetic", description: "Products used for nausea and vomiting" },
  { name: "Laxative", description: "Products used for constipation relief" },
  { name: "Antihypertensive", description: "Products used to manage high blood pressure" },
  { name: "Antidiabetic", description: "Products used to manage diabetes" },
  { name: "Vitamin", description: "Vitamin preparations and supplements" },
  { name: "Mineral Supplement", description: "Mineral preparations and supplements" },
  { name: "Food Supplement", description: "Nutrition and wellness supplements" },
  { name: "Ophthalmic", description: "Products for eye use" },
  { name: "Otic", description: "Products for ear use" },
  { name: "Topical Antibiotic", description: "Antibiotic products for skin use" },
  { name: "Topical Antifungal", description: "Antifungal products for skin use" },
  { name: "Topical Corticosteroid", description: "Corticosteroid products for skin use" },
  { name: "Topical Analgesic", description: "Pain relief products for skin use" },
];
